-- Volleyball Drill Library — 36 drills across all skill types
-- Run in Supabase SQL Editor

INSERT INTO drills (organization_id, created_by, name, description, instructions, skill_type, positions_relevant, difficulty, training_phase_tags, equipment_required, video_url, coaching_cues, is_public) VALUES

-- ─── SERVING ──────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Serving Target Practice',
 'Serve to marked zones on the opposite court to improve accuracy and consistency.',
 E'1. Mark 6 zones on opposite court with tape\n2. Serve 10 balls to each zone\n3. Track successful serves per zone\n4. Repeat for 3 sets',
 'serving', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['court','cones','volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+serving+target+practice+drill',
 '["Contact high and consistent","Follow through toward target","Adjust toss placement","Maintain court position"]'::jsonb, true),

(NULL, NULL,
 'Float Serve Technique Drill',
 'Practice no-spin knuckleball serve for unpredictable ball movement.',
 E'1. Stand 10 feet from wall\n2. Perform 15 float serves against wall\n3. Move back 5 feet, repeat\n4. Progress to full service line',
 'serving', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['wall','volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+float+serve+drill',
 '["Minimal wrist action","Direct arm swing","Firm center contact","Consistent toss height"]'::jsonb, true),

(NULL, NULL,
 'Serve and Move',
 'Serve then quickly move to defensive position to build transition readiness.',
 E'1. Serve from baseline\n2. Sprint to defensive position immediately\n3. Hold ready position for 3 seconds\n4. Repeat 10 times',
 'serving', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'intermediate', ARRAY['competition_maintenance']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+serve+and+move+transition+drill',
 '["Quick footwork after serve","Low athletic position","Eyes on the net","Ready to react"]'::jsonb, true),

-- ─── PASSING ──────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Pepper Drill',
 'Two-player pass-set-hit warm-up to build touch, control and consistency.',
 E'1. Two players face each other 10 feet apart\n2. Player A passes to Player B\n3. Player B sets back to Player A\n4. Player A attacks back\n5. Repeat continuously for 1 minute',
 'passing', ARRAY['libero','outside_hitter','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+pepper+drill',
 '["Soft controlled hands","Keep ball high","Constant communication","Smooth transitions"]'::jsonb, true),

(NULL, NULL,
 'Platform Pass Progression',
 'Solo wall drill isolating platform contact mechanics with progressive distance.',
 E'1. Stand 5 feet from wall\n2. Pass 10 balls focusing on platform shape\n3. Move back 3 feet, repeat\n4. Continue to full court depth',
 'passing', ARRAY['libero','outside_hitter','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['wall','volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+platform+pass+wall+drill',
 '["Flat firm platform","Bent knees","Level shoulders","Straight arms at contact"]'::jsonb, true),

(NULL, NULL,
 'Libero Passing Patterns',
 'Movement-focused passing drill for liberos reacting to multiple angles.',
 E'1. Libero starts in back center\n2. Coach tosses balls from varying angles\n3. Pass to setter target position\n4. Shuffle to next base, repeat 15 reps',
 'passing', ARRAY['libero']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+libero+passing+movement+drill',
 '["Aggressive first step","Quick shuffle feet","High pass to setter zone","Balanced finish"]'::jsonb, true),

(NULL, NULL,
 'Pass and Call',
 'Practice verbal communication while receiving serve pressure.',
 E'1. Partner serves from service line\n2. Receiver calls the ball loudly\n3. Pass to setter target\n4. Rotate after 5 passes each',
 'passing', ARRAY['libero','outside_hitter','middle_blocker','defensive_specialist']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+passing+communication+drill',
 '["Call the ball early","Clear loud voice","Commit fully","Move feet first"]'::jsonb, true),

-- ─── SETTING ──────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Setting Wall Drill',
 'Solo drill building setting consistency against a wall at varying distances.',
 E'1. Stand 5 feet from wall\n2. Set 15 balls against wall\n3. Move back 2 feet, repeat\n4. Vary arc height: low, medium, high',
 'setting', ARRAY['setter']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['wall','volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+setting+wall+drill',
 '["Soft hands","Contact above forehead","High consistent release","Smooth wrist action"]'::jsonb, true),

(NULL, NULL,
 'High Ball Setting',
 'Set high arcs for outside hitters from various pass locations.',
 E'1. Passer delivers ball to setter\n2. Setter sets high ball to outside position\n3. Hitter takes controlled swing\n4. Repeat 10 reps per side',
 'setting', ARRAY['setter']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+high+ball+outside+set+drill',
 '["High apex trajectory","Proper distance from net","Consistent release point","Quick hands"]'::jsonb, true),

(NULL, NULL,
 'Quick Set to Middle',
 'Develop fast tempo sets to middle blockers for attacking variety.',
 E'1. Passer delivers pass to setter\n2. Setter delivers quick low ball to middle\n3. Middle attacks\n4. Rotate setters every 10 reps',
 'setting', ARRAY['setter']::volleyball_position[],
 'advanced', ARRAY['competition_maintenance']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+quick+set+middle+blocker+drill',
 '["Lightning-fast hands","Ball stays low","Early contact","Precise location"]'::jsonb, true),

(NULL, NULL,
 'Five-Zone Setting',
 'Set to all five attack positions from varied pass angles.',
 E'1. Passers deliver from 5 positions\n2. Setter adjusts and sets designated zone\n3. Hitter attacks\n4. Rotate all positions',
 'setting', ARRAY['setter']::volleyball_position[],
 'advanced', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+five+zone+setting+drill',
 '["Read pass early","Quick foot adjustment","Consistent set quality","Proper spacing"]'::jsonb, true),

-- ─── ATTACKING ────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Four-Step Approach Jump',
 'Master the four-step attack approach with timing and explosive jump.',
 E'1. Start 8 feet from net\n2. Execute right-left-right-left (or left-right-left-right) approach\n3. Jump and contact set ball at peak\n4. Land safely on both feet, reset',
 'attacking', ARRAY['outside_hitter','opposite','middle_blocker']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+four+step+approach+attack+drill',
 '["Explosive penultimate step","Time jump with setter","Full arm swing","Controlled two-foot landing"]'::jsonb, true),

(NULL, NULL,
 'Line and Cross Attack',
 'Attack down the line and cross-court alternately to build placement control.',
 E'1. Setter delivers outside set\n2. First rep attack down the line\n3. Second rep attack cross-court\n4. Alternate for 20 reps total',
 'attacking', ARRAY['outside_hitter','opposite']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['volleyball','net','cones'],
 'https://www.youtube.com/results?search_query=volleyball+line+and+cross+attack+drill',
 '["Contact point determines angle","Open or close shoulder","Wrist snap at contact","Watch for blockers"]'::jsonb, true),

(NULL, NULL,
 'Attack Against Block',
 'Hit around and over a standing blocker to develop angle awareness.',
 E'1. Blocker stands at net in ready position\n2. Hitter approaches and attacks\n3. Hit around or over the block\n4. Rotate positions every 5 reps',
 'attacking', ARRAY['outside_hitter','opposite','middle_blocker']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['volleyball','net'],
 'https://www.youtube.com/results?search_query=volleyball+hitting+against+block+drill',
 '["Read block early","Tool the block","Cut angle sharply","Wipe off hands"]'::jsonb, true),

(NULL, NULL,
 'Back Row Attack (Pipe)',
 'Develop back row attacking from the middle back (pipe) position.',
 E'1. Attacker starts at back row middle\n2. Approach and jump behind 3-meter line\n3. Attack set ball over net\n4. 15 reps, track net violations',
 'attacking', ARRAY['outside_hitter','opposite']::volleyball_position[],
 'advanced', ARRAY['competition_maintenance']::training_phase[], ARRAY['volleyball','net','cones'],
 'https://www.youtube.com/results?search_query=volleyball+back+row+pipe+attack+drill',
 '["Jump behind 3m line","High contact point","Strong arm swing","Aggressive approach"]'::jsonb, true),

-- ─── BLOCKING ─────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Blocking Footwork Shuffle',
 'Build lateral blocking footwork and explosive jump from various positions.',
 E'1. Start at center net position\n2. Shuffle right 3 steps, jump block\n3. Return to center\n4. Shuffle left 3 steps, jump block\n5. Repeat continuously for 1 minute',
 'blocking', ARRAY['middle_blocker','outside_hitter','opposite']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['net','cones'],
 'https://www.youtube.com/results?search_query=volleyball+blocking+footwork+shuffle+drill',
 '["Low shuffle stance","Explosive jump","Hands high and wide","Balanced landing"]'::jsonb, true),

(NULL, NULL,
 'Read and Block',
 'React to hitter approach angle and seal the correct block position.',
 E'1. Coach signals hitter position\n2. Blocker reads approach and moves\n3. Jump and block at correct angle\n4. Rotate hitters through positions',
 'blocking', ARRAY['middle_blocker','outside_hitter','opposite']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['net','volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+read+and+block+drill',
 '["Watch hitter shoulders","Commit to one side","Penetrate over net","Firm wrists"]'::jsonb, true),

(NULL, NULL,
 'Three-Person Block Coordination',
 'Build communication and timing between three blockers sealing the net.',
 E'1. Three blockers set at net positions\n2. Coach tosses to hitter at random positions\n3. All three blockers shift and seal\n4. Outside blocker calls line or angle',
 'blocking', ARRAY['middle_blocker','outside_hitter','opposite']::volleyball_position[],
 'advanced', ARRAY['competition_maintenance']::training_phase[], ARRAY['net','volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+triple+block+coordination+drill',
 '["Communicate line or angle","Close the seam","Move as a unit","Eyes on the hitter"]'::jsonb, true),

-- ─── DEFENSE ──────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Defensive Sliding and Passing',
 'Lateral shuffle movement to balls left and right with controlled passes.',
 E'1. Start in back center defensive base\n2. Coach tosses ball to left\n3. Shuffle and forearm pass\n4. Return to base, repeat right\n5. 20 total reps',
 'defense', ARRAY['libero','defensive_specialist','outside_hitter','middle_blocker','opposite']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+defensive+lateral+sliding+drill',
 '["Stay low and wide","Shuffle, do not cross feet","Platform to target","Call the ball"]'::jsonb, true),

(NULL, NULL,
 'Deep Court Retrieval',
 'Sprint to retrieve deep attacked balls and pass back to setter target.',
 E'1. Defender starts at 3-meter line\n2. Coach hits ball deep to baseline\n3. Sprint full effort to retrieve\n4. Pass to setter position\n5. Reset, 12 reps',
 'defense', ARRAY['libero','defensive_specialist','outside_hitter','middle_blocker','opposite']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['volleyball','cones'],
 'https://www.youtube.com/results?search_query=volleyball+deep+court+retrieval+defense+drill',
 '["Full sprint commitment","Get under the ball","High controlled pass","Call every ball"]'::jsonb, true),

(NULL, NULL,
 'Sprawl and Recover',
 'Dive or sprawl to defend hard attacks then immediately recover to base.',
 E'1. Player in defensive stance\n2. Coach attacks hard left or right\n3. Sprawl and dig ball up\n4. Immediately recover to base position\n5. 10 reps each side',
 'defense', ARRAY['libero','defensive_specialist']::volleyball_position[],
 'advanced', ARRAY['general']::training_phase[], ARRAY['volleyball','knee pads'],
 'https://www.youtube.com/results?search_query=volleyball+sprawl+dive+defense+drill',
 '["Extend fully on floor","Keep platform angle up","Fast recovery","Protect the ball first"]'::jsonb, true),

(NULL, NULL,
 'Block-Defense Coordination',
 'Coordinate back-court defense with front-row block to cover all angles.',
 E'1. Two blockers at net in ready position\n2. Three back defenders in base\n3. Hitter attacks\n4. Block takes angle, defense covers the rest\n5. Rotate positions every 3 rallies',
 'defense', ARRAY['libero','defensive_specialist','outside_hitter','middle_blocker','opposite']::volleyball_position[],
 'advanced', ARRAY['competition_maintenance']::training_phase[], ARRAY['volleyball','net','cones'],
 'https://www.youtube.com/results?search_query=volleyball+block+defense+coordination+drill',
 '["Block seals one angle","Defenders shift to cover","Constant talking","Ready for tips"]'::jsonb, true),

-- ─── CONDITIONING ─────────────────────────────────────────────────────────────
(NULL, NULL,
 'Court Sprint Intervals',
 'Baseline-to-baseline sprints with walk recovery to build speed endurance.',
 E'1. Sprint from baseline to baseline\n2. Walk back to recover\n3. Repeat 10 times\n4. Rest 60 seconds\n5. Complete 3 total sets',
 'conditioning', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['court','cones'],
 'https://www.youtube.com/results?search_query=volleyball+sprint+interval+conditioning',
 '["Maximum effort each rep","Controlled decel at end","Full recovery between sets","Drive arms hard"]'::jsonb, true),

(NULL, NULL,
 'Agility Ladder Footwork',
 'Multi-pattern footwork through agility ladder for speed and coordination.',
 E'1. Set up 10-rung ladder on court\n2. Run: high knees, lateral shuffle, Icky shuffle\n3. 4 passes through per pattern\n4. Rest 30 seconds between patterns\n5. Complete 3 patterns',
 'conditioning', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['agility ladder','cones'],
 'https://www.youtube.com/results?search_query=volleyball+agility+ladder+footwork+drill',
 '["Quick light feet","Precise foot placement","Arms assist movement","Increase speed each pass"]'::jsonb, true),

(NULL, NULL,
 'Jump Rope Power Intervals',
 'Build explosive calf and leg power with jump rope conditioning circuits.',
 E'1. Jump rope single-bounce 30 seconds\n2. Rest 15 seconds\n3. Attempt double-unders 30 seconds\n4. Rest 15 seconds\n5. Complete 5 full rounds',
 'conditioning', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['jump rope'],
 'https://www.youtube.com/results?search_query=volleyball+jump+rope+conditioning+workout',
 '["Land on balls of feet","Relaxed wrist rotation","Consistent rhythm","Stay tall"]'::jsonb, true),

(NULL, NULL,
 '300 Touches Wall Challenge',
 'Consecutive wall passes against the clock to build endurance and focus.',
 E'1. Stand 4 feet from wall\n2. Forearm pass continuously against wall\n3. Count 300 consecutive touches\n4. Rest 2 minutes if ball drops\n5. Track personal record',
 'conditioning', ARRAY['libero','defensive_specialist','outside_hitter','middle_blocker','opposite']::volleyball_position[],
 'intermediate', ARRAY['general']::training_phase[], ARRAY['wall','volleyball'],
 'https://www.youtube.com/results?search_query=volleyball+wall+passing+endurance+challenge',
 '["Consistent platform angle","Maintain knee bend","Breathe steadily","Focus on the ball"]'::jsonb, true),

-- ─── STRENGTH ─────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Medicine Ball Rotational Throw',
 'Explosive rotational core power training for attacking and serving.',
 E'1. Stand sideways 3 feet from wall\n2. Hold medicine ball at hip\n3. Rotate explosively and throw wall\n4. Catch and decelerate\n5. 12 reps each side',
 'strength', ARRAY['setter','outside_hitter','opposite','middle_blocker']::volleyball_position[],
 'intermediate', ARRAY['strength']::training_phase[], ARRAY['medicine ball','wall'],
 'https://www.youtube.com/results?search_query=volleyball+medicine+ball+rotational+power+drill',
 '["Initiate from hips","Explosive hip rotation","Follow through fully","Controlled catch"]'::jsonb, true),

(NULL, NULL,
 'Plyometric Box Jumps',
 'Build leg explosiveness and jump height for blocking and attacking.',
 E'1. Stand facing 20-24 inch box\n2. Dip and explode onto box\n3. Land softly on both feet\n4. Step down, reset\n5. 8 reps x 3 sets, rest 90 seconds',
 'strength', ARRAY['outside_hitter','opposite','middle_blocker']::volleyball_position[],
 'intermediate', ARRAY['strength']::training_phase[], ARRAY['plyometric box'],
 'https://www.youtube.com/results?search_query=volleyball+plyometric+box+jump+training',
 '["Arm swing drives jump","Land with soft knees","Full hip extension","Step down, never jump down"]'::jsonb, true),

(NULL, NULL,
 'Shoulder Press and Stability',
 'Overhead pressing strength and stability for blocking and attacking power.',
 E'1. Stand with dumbbells at shoulder height\n2. Press overhead to full extension\n3. Hold 1 second at top\n4. Lower slowly to start\n5. 10 reps x 3 sets',
 'strength', ARRAY['setter','outside_hitter','opposite','middle_blocker']::volleyball_position[],
 'intermediate', ARRAY['strength']::training_phase[], ARRAY['dumbbell'],
 'https://www.youtube.com/results?search_query=volleyball+shoulder+press+strength+training',
 '["Brace the core","Full overhead extension","Slow eccentric","Neutral spine"]'::jsonb, true),

(NULL, NULL,
 'Single-Leg Squat (Bulgarian Split Squat)',
 'Build unilateral leg strength and balance for explosive movements.',
 E'1. Rear foot elevated on bench\n2. Lower front knee toward floor\n3. Front knee stays over toes\n4. Drive through heel to stand\n5. 10 reps each leg x 3 sets',
 'strength', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'intermediate', ARRAY['strength']::training_phase[], ARRAY['bench','dumbbell'],
 'https://www.youtube.com/results?search_query=volleyball+bulgarian+split+squat+strength',
 '["Front shin vertical","Full depth","Drive through heel","Controlled tempo"]'::jsonb, true),

-- ─── MOBILITY ─────────────────────────────────────────────────────────────────
(NULL, NULL,
 'Shoulder Mobility Flow',
 'Progressive shoulder mobility sequence to reduce injury risk and improve range.',
 E'1. Arm circles forward x10\n2. Arm circles backward x10\n3. Cross-body shoulder stretch 20 sec each\n4. Doorway pec stretch 20 sec\n5. Behind-back reach 20 sec each arm',
 'mobility', ARRAY['setter','outside_hitter','opposite','middle_blocker']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['exercise mat'],
 'https://www.youtube.com/results?search_query=volleyball+shoulder+mobility+warm+up+routine',
 '["Pain-free range only","No bouncing","Breathe into stretch","Progressive depth"]'::jsonb, true),

(NULL, NULL,
 'Hip Flexor and Hamstring Routine',
 'Open hips and stretch hamstrings for better court movement and power.',
 E'1. Hip flexor lunge stretch 30 sec each\n2. Standing hamstring stretch 30 sec each\n3. Seated forward fold 30 sec\n4. Pigeon pose 30 sec each hip\n5. Deep squat hold 30 sec',
 'mobility', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['exercise mat'],
 'https://www.youtube.com/results?search_query=volleyball+hip+flexor+hamstring+stretch+routine',
 '["Exhale into stretch","Feel not pain","Hold each position","Relax the muscle"]'::jsonb, true),

(NULL, NULL,
 'Ankle Stability and Mobility Circuit',
 'Strengthen ankles and improve range to prevent sprains and improve agility.',
 E'1. Ankle alphabet (trace A-Z with foot) each ankle\n2. Banded dorsiflexion 15 reps each\n3. Single-leg balance 30 sec each\n4. Heel raises on edge of step x 20\n5. Lateral ankle hops 10 each direction',
 'mobility', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['resistance band','step'],
 'https://www.youtube.com/results?search_query=volleyball+ankle+stability+mobility+exercises',
 '["Full range of motion","Control the movement","Build gradually","Strengthen through range"]'::jsonb, true),

(NULL, NULL,
 'Full-Body Dynamic Warm-Up',
 'Complete pre-practice warm-up activating all joints and muscle groups.',
 E'1. Jog 2 laps of court\n2. Arm circles + band pull-aparts x10\n3. Leg swings front/back and side x10 each\n4. Walking lunge with thoracic rotation x10\n5. Inchworm push-up x8\n6. Lateral shuffle + carioca 2x each end',
 'mobility', ARRAY['setter','libero','outside_hitter','opposite','middle_blocker','defensive_specialist']::volleyball_position[],
 'beginner', ARRAY['general']::training_phase[], ARRAY['resistance band','cones'],
 'https://www.youtube.com/results?search_query=volleyball+full+body+dynamic+warm+up+routine',
 '["Gradual intensity increase","Full joint range","Smooth transitions","Build to practice pace"]'::jsonb, true);
