-- Volleyball Drill Library SQL
-- Insert 30+ drills into the drills table
-- Run this in Supabase SQL Editor after creating the schema

-- Serving Drills
INSERT INTO drills (organization_id, created_by, name, description, instructions, skill_type, positions_relevant, difficulty, training_phase_tags, equipment_required, video_url, video_thumbnail_url, coaching_cues, is_public)
VALUES
  (NULL, NULL, 'Serving Target Practice', 'Serve to marked zones on the opposite court to improve accuracy and consistency.', '1. Mark 6 zones on opposite court with tape\n2. Serve 10 balls to each zone\n3. Track successful serves in each zone\n4. Repeat for 3 sets', 'serving', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['court', 'cones', 'volleyball'], 'https://www.youtube.com/results?search_query=volleyball+serving+target+practice+drill', NULL, '["Contact high and consistent", "Follow through toward target", "Adjust toss placement", "Maintain court position"]'::jsonb, true),

  (NULL, NULL, 'Float Serve Technique Drill', 'Practice knuckleball serve with no spin for unpredictable movement.', '1. Stand 10 feet from wall\n2. Perform 15 float serves against wall\n3. Move back 5 feet, repeat\n4. Progress to service line', 'serving', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['general'], ARRAY['wall', 'volleyball'], 'https://www.youtube.com/results?search_query=volleyball+float+serve+drill', NULL, '["Minimal wrist action", "Direct arm swing", "Firm contact center of ball", "Consistent toss height"]'::jsonb, true),

  (NULL, NULL, 'Serve and Move', 'Serve then quickly move to defensive position to develop transition readiness.', '1. Serve from baseline\n2. Immediately move to defensive position\n3. Hold position for 3 seconds\n4. Repeat 10 times', 'serving', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['competition_maintenance'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+serve+and+move+drill', NULL, '["Quick footwork after serve", "Low athletic position", "Ready to react", "Eyes on net"]'::jsonb, true),

-- Passing Drills
  (NULL, NULL, 'Pepper Drill', 'Two-player warm-up involving pass-set-hit sequences to develop control and consistency.', '1. Two players face each other 10 feet apart\n2. Player A passes to Player B\n3. Player B sets to Player A\n4. Player A hits back to Player B\n5. Repeat for 1 minute', 'passing', ARRAY['libero', 'outside_hitter', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['volleyball'], 'https://www.youtube.com/results?search_query=volleyball+pepper+drill', NULL, '["Soft hands", "High passes", "Communication", "Smooth transitions"]'::jsonb, true),

  (NULL, NULL, 'Platform Pass Progression', 'Solo drill isolating platform contact mechanics with progressive difficulty.', '1. Stand 5 feet from wall\n2. Pass 10 balls against wall, focusing on platform\n3. Move back 3 feet, repeat\n4. Continue progressing back to service line', 'passing', ARRAY['libero', 'outside_hitter', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['wall', 'volleyball'], 'https://www.youtube.com/results?search_query=volleyball+platform+pass+wall+drill', NULL, '["Flat platform", "Bent knees", "Level shoulders", "Straight arms"]'::jsonb, true),

  (NULL, NULL, 'Libero Passing Patterns', 'Specialized passing drills for libero with movement and positioning focus.', '1. Libero starts in back center\n2. Coach throws balls from various angles\n3. Pass to setter position\n4. Shuffle to next position, repeat', 'passing', ARRAY['libero'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+libero+passing+drill', NULL, '["Quick feet", "Aggressive first step", "High passes to setter", "Balance and control"]'::jsonb, true),

  (NULL, NULL, 'Pass and Communicate', 'Emphasize verbal communication while passing difficult serves.', '1. Partner serves from service line\n2. Receiver passes and calls the ball\n3. Setter takes pass\n4. Rotate positions after 5 passes', 'passing', ARRAY['libero', 'outside_hitter', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+passing+communication+drill', NULL, '["Call the ball early", "Clear voice", "Trust teammates", "Move to ball"]'::jsonb, true),

-- Setting Drills
  (NULL, NULL, 'Setting Wall Drill', 'Solo drill practicing sets against a wall at various distances and heights.', '1. Stand 5 feet from wall\n2. Set 15 balls against wall in control\n3. Move back 2 feet, repeat\n4. Vary heights: low, medium, high', 'setting', ARRAY['setter'], 'beginner', ARRAY['general'], ARRAY['wall', 'volleyball'], 'https://www.youtube.com/results?search_query=volleyball+setting+wall+drill', NULL, '["Soft hands", "High release", "Smooth motion", "Contact above forehead"]'::jsonb, true),

  (NULL, NULL, 'High Ball Setting', 'Practice setting high arcs for outside hitters with varying distances.', '1. Passer delivers pass to setter\n2. Setter delivers high ball to outside position\n3. Hitter takes swing (controlled)\n4. Repeat 10 times per side', 'setting', ARRAY['setter'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+high+ball+setting+drill', NULL, '["High arc for hitter", "Proper distance from net", "Consistent release", "Quick hands"]'::jsonb, true),

  (NULL, NULL, 'Quick Set to Middle', 'Develop quick-tempo sets to middle blockers for attacking options.', '1. Passer delivers pass to setter\n2. Setter delivers quick ball to middle\n3. Middle attacks or blocks\n4. Rotate through all setters', 'setting', ARRAY['setter'], 'advanced', ARRAY['competition_maintenance'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+quick+set+middle+drill', NULL, '["Fast hands", "Low ball", "Early contact", "Precise location"]'::jsonb, true),

  (NULL, NULL, 'Five-Zone Setting', 'Practice setting to all five attacking positions from various pass locations.', '1. Passers deliver from 5 different positions\n2. Setter adjusts and sets to designated position\n3. Hitter attacks\n4. Rotate positions', 'setting', ARRAY['setter'], 'advanced', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+five+zone+setting+drill', NULL, '["Read the pass early", "Quick feet adjustment", "Consistent sets", "Proper spacing"]'::jsonb, true),

-- Attacking/Hitting Drills
  (NULL, NULL, 'Approach Jump Attack', 'Practice four-step approach footwork with jump training and arm swing.', '1. Start 8 feet from net\n2. Execute 4-step approach\n3. Jump and attack set ball\n4. Land safely, reset position', 'attacking', ARRAY['outside_hitter', 'opposite', 'middle_blocker'], 'beginner', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+approach+jump+attack+drill', NULL, '["Explosive jump", "Timing with setter", "Follow through", "Controlled landing"]'::jsonb, true),

  (NULL, NULL, 'One-Meter Attack Drill', 'Attack from one meter away from net to develop power and accuracy.', '1. Start 1 meter from net\n2. Approach and attack set ball\n3. Aim for cross-court target\n4. Repeat 15 times, track successful attacks', 'attacking', ARRAY['outside_hitter', 'opposite', 'middle_blocker'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'cones', 'net'], 'https://www.youtube.com/results?search_query=volleyball+one+meter+attack+drill', NULL, '["Aggressive contact", "Downward angle", "Arm follow-through", "Precision placement"]'::jsonb, true),

  (NULL, NULL, 'Attack Against Block', 'Practice attacking with a defender at net to develop angle awareness.', '1. Blocker at net in ready position\n2. Hitter approaches and attacks\n3. Attempt to hit around or over block\n4. Rotate positions', 'attacking', ARRAY['outside_hitter', 'opposite', 'middle_blocker'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'net', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+attack+against+block+drill', NULL, '["Read the block", "Adjust angle", "Hit away from defender", "Ball control"]'::jsonb, true),

  (NULL, NULL, 'Cross-Court Attack', 'Develop attacking angles across the court for unpredictable offense.', '1. Setter delivers set to hitter\n2. Hitter attacks cross-court\n3. Ball must land in opposing cross-court zone\n4. Repeat 20 times, track success rate', 'attacking', ARRAY['outside_hitter', 'opposite'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'net', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+cross+court+attack+drill', NULL, '["Early contact point", "Lateral arm swing", "Downward trajectory", "Consistent placement"]'::jsonb, true),

-- Blocking Drills
  (NULL, NULL, 'Blocking Footwork Drill', 'Develop blocking footwork patterns and positioning at the net.', '1. Start in center position\n2. Shuffle right, jump block\n3. Return center, shuffle left, jump block\n4. Continue for 1 minute', 'blocking', ARRAY['middle_blocker', 'outside_hitter', 'opposite'], 'beginner', ARRAY['general'], ARRAY['net', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+blocking+footwork+drill', NULL, '["Quick shuffle steps", "Explosive jump", "Hands high", "Balanced landing"]'::jsonb, true),

  (NULL, NULL, 'Block Transitions', 'Practice blocking followed by quick transition to defense.', '1. Block at net (hitter approaches)\n2. Immediately drop back to defensive position\n3. Defend approaching attack\n4. Reset for next block', 'blocking', ARRAY['middle_blocker', 'outside_hitter', 'opposite'], 'intermediate', ARRAY['general'], ARRAY['net', 'volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+block+transition+drill', NULL, '["Hands ready", "Eyes on hitter", "Quick feet", "Attack mindset"]'::jsonb, true),

  (NULL, NULL, 'Shoulder Block', 'Build strong blocking technique with shoulder positioning and arm mechanics.', '1. Two blockers at net\n2. Coach tosses ball to hitter\n3. Blockers attempt to seal block\n4. Track successful blocks per round', 'blocking', ARRAY['middle_blocker', 'outside_hitter', 'opposite'], 'intermediate', ARRAY['general'], ARRAY['net', 'volleyball'], 'https://www.youtube.com/results?search_query=volleyball+shoulder+block+technique+drill', NULL, '["Hands tight together", "Shoulders forward", "Block the line", "Seal the block"]'::jsonb, true),

  (NULL, NULL, 'Three-Person Block Drill', 'Develop communication and coordination among three blockers.', '1. Three blockers at net\n2. Coach tosses to hitter at different positions\n3. Blockers adjust and seal block\n4. Rotate hitter through positions', 'blocking', ARRAY['middle_blocker', 'outside_hitter', 'opposite'], 'advanced', ARRAY['competition_maintenance'], ARRAY['net', 'volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+three+person+block+drill', NULL, '["Communicate early", "Seal gaps", "Move together", "Eyes on hitter"]'::jsonb, true),

-- Defense Drills
  (NULL, NULL, 'Defensive Sliding Drill', 'Practice lateral movement and defensive positioning with controlled sliding.', '1. Start in center back position\n2. Coach tosses ball left\n3. Shuffle and pass left\n4. Return center, repeat right', 'defense', ARRAY['libero', 'defensive_specialist', 'middle_blocker', 'outside_hitter', 'opposite'], 'beginner', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+defensive+sliding+drill', NULL, '["Stay low", "Shuffle not cross-step", "Soft hands", "Pass high"]'::jsonb, true),

  (NULL, NULL, 'Deep Court Defense', 'Develop defensive skills for balls traveling deep into back court.', '1. Coach throws or hits balls deep\n2. Defender sprints and retrieves\n3. Pass to target position\n4. Repeat from different angles', 'defense', ARRAY['libero', 'defensive_specialist', 'middle_blocker', 'outside_hitter', 'opposite'], 'intermediate', ARRAY['general'], ARRAY['volleyball', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+deep+court+defense+drill', NULL, '["Full sprint", "Controlled approach", "Low pass", "Communication"]'::jsonb, true),

  (NULL, NULL, 'One-Touch Passing', 'Practice redirecting attacks with quick defensive touches.', '1. Attacker hits ball at defender\n2. Defender performs one-touch pass\n3. Pass directed to setter\n4. Repeat 15 times', 'defense', ARRAY['libero', 'defensive_specialist', 'middle_blocker', 'outside_hitter', 'opposite'], 'advanced', ARRAY['general'], ARRAY['volleyball', 'net'], 'https://www.youtube.com/results?search_query=volleyball+one+touch+passing+defense+drill', NULL, '["Quick hands", "Reaction time", "Soft touch", "Precise direction"]'::jsonb, true),

  (NULL, NULL, 'Defensive Coverage Patterns', 'Team defensive positioning and communication for block coverage.', '1. Three blockers at net\n2. Three back court defenders in position\n3. Hitter attacks\n4. Defense positions for blocked ball coverage', 'defense', ARRAY['libero', 'defensive_specialist', 'middle_blocker', 'outside_hitter', 'opposite'], 'advanced', ARRAY['general'], ARRAY['volleyball', 'net', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+defensive+coverage+drill', NULL, '["Position early", "Anticipate block", "Talk constantly", "Ready to pass"]'::jsonb, true),

-- Conditioning Drills
  (NULL, NULL, 'Court Sprint Intervals', 'Build court speed and cardiovascular endurance with short sprints.', '1. Sprint baseline to baseline\n2. Walk back to reset\n3. Repeat 10 times\n4. Rest 60 seconds, do 3 sets', 'conditioning', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['court', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+court+sprints+conditioning', NULL, '["Maximum effort", "Controlled deceleration", "Quick recovery", "Proper form"]'::jsonb, true),

  (NULL, NULL, 'Ladder Footwork Agility', 'Improve foot speed and agility using agility ladder.', '1. Set up agility ladder on court\n2. Perform various footwork patterns through ladder\n3. Single-leg hoppers, high knees, shuffle steps\n4. 4 passes through, rest 30 seconds, repeat 3x', 'conditioning', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['agility ladder', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+ladder+footwork+agility+drill', NULL, '["Quick feet", "Precision placement", "Consistent tempo", "Arms engaged"]'::jsonb, true),

  (NULL, NULL, 'Jump Rope Conditioning', 'Build explosive power and coordination with jump rope training.', '1. Single rope jumping for 30 seconds\n2. Rest 15 seconds\n3. Double-under attempts for 30 seconds\n4. Complete 5 rounds', 'conditioning', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['general'], ARRAY['jump rope'], 'https://www.youtube.com/results?search_query=volleyball+jump+rope+conditioning', NULL, '["Quick wrist rotation", "Consistent rhythm", "Land softly", "Maintain posture"]'::jsonb, true),

  (NULL, NULL, 'Push Pass Endurance', 'Develop shoulder and leg endurance through repeated passing.', '1. Perform 20 continuous passes against wall\n2. Rest 15 seconds\n3. Repeat for 5 sets\n4. Progress to 30 passes per set', 'conditioning', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['general'], ARRAY['wall', 'volleyball'], 'https://www.youtube.com/results?search_query=volleyball+pass+endurance+conditioning', NULL, '["Consistent platform", "Maintain form", "Breathing rhythm", "Focus on accuracy"]'::jsonb, true),

-- Strength Drills
  (NULL, NULL, 'Medicine Ball Rotational Throws', 'Build core strength and rotational power for attacking and blocking.', '1. Stand sideways to wall, 3 feet away\n2. Hold medicine ball at chest\n3. Rotate and throw explosively at wall\n4. Catch and return, 12 reps per side', 'strength', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['strength'], ARRAY['medicine ball', 'wall'], 'https://www.youtube.com/results?search_query=volleyball+medicine+ball+rotational+throw', NULL, '["Explosive rotation", "Core engagement", "Follow through", "Controlled catch"]'::jsonb, true),

  (NULL, NULL, 'Plyometric Box Jumps', 'Develop explosive leg power for jumping and attacking.', '1. Stand facing 24-inch box\n2. Jump onto box with both feet\n3. Step down safely\n4. Rest, repeat 8 times for 3 sets', 'strength', ARRAY['outside_hitter', 'opposite', 'middle_blocker'], 'intermediate', ARRAY['strength'], ARRAY['plyometric box'], 'https://www.youtube.com/results?search_query=volleyball+plyometric+box+jump+training', NULL, '["Explosive takeoff", "Land softly", "Arms up", "Quick recovery"]'::jsonb, true),

  (NULL, NULL, 'Push-Ups with Reach', 'Strengthen shoulders and chest for attacking and blocking power.', '1. Get in push-up position\n2. Lower body, press up explosively\n3. One arm reaches forward at top\n4. Alternate arms, 12 reps total', 'strength', ARRAY['setter', 'outside_hitter', 'opposite', 'middle_blocker'], 'beginner', ARRAY['strength'], ARRAY['exercise mat'], 'https://www.youtube.com/results?search_query=volleyball+push+up+reaching+strength', NULL, '["Full body tension", "Explosive press", "Controlled reach", "Stable core"]'::jsonb, true),

  (NULL, NULL, 'Single-Leg Deadlifts', 'Build leg strength and stability for balance and power generation.', '1. Stand on one leg, slight knee bend\n2. Hinge forward at hips\n3. Lower weight toward floor\n4. Return to standing, 10 reps per leg', 'strength', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'intermediate', ARRAY['strength'], ARRAY['dumbbell'], 'https://www.youtube.com/results?search_query=volleyball+single+leg+deadlift+strength', NULL, '["Maintain balance", "Hinge at hips", "Keep chest up", "Controlled tempo"]'::jsonb, true),

-- Mobility Drills
  (NULL, NULL, 'Shoulder Mobility Flow', 'Increase shoulder range of motion and reduce injury risk.', '1. Arm circles forward 10 reps\n2. Arm circles backward 10 reps\n3. Cross-body shoulder stretch 10 sec per side\n4. Behind-back shoulder reach 10 sec per side', 'mobility', ARRAY['setter', 'outside_hitter', 'opposite', 'middle_blocker'], 'beginner', ARRAY['general'], ARRAY['exercise mat'], 'https://www.youtube.com/results?search_query=volleyball+shoulder+mobility+stretch', NULL, '["Controlled movements", "No bouncing", "Deep stretch", "Breathe slowly"]'::jsonb, true),

  (NULL, NULL, 'Hip and Hamstring Flexibility', 'Improve lower body flexibility for better range of motion and power.', '1. Quad stretch 20 seconds per leg\n2. Hamstring stretch 20 seconds per leg\n3. Pigeon pose 30 seconds per side\n4. Deep squat hold 30 seconds', 'mobility', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['exercise mat'], 'https://www.youtube.com/results?search_query=volleyball+hip+hamstring+flexibility+stretch', NULL, '["Controlled breathing", "No pain", "Hold steady", "Progressive depth"]'::jsonb, true),

  (NULL, NULL, 'Ankle Mobility Series', 'Strengthen ankles and improve mobility for stability and injury prevention.', '1. Ankle circles both directions 10 times\n2. Heel-to-toe walks 20 meters\n3. Single-leg balance 30 seconds per leg\n4. Calf raises 15 reps', 'mobility', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['exercise mat', 'cones'], 'https://www.youtube.com/results?search_query=volleyball+ankle+mobility+exercises', NULL, '["Full range motion", "Control movement", "Balance challenge", "Strength focus"]'::jsonb, true),

  (NULL, NULL, 'Full Body Dynamic Warm-Up', 'Comprehensive warm-up combining mobility and activation for all movement planes.', '1. Arm circles and band pull-aparts\n2. Leg swings forward/back and side-to-side\n3. Walking lunges with rotation\n4. Inchworms and push-up to downward dog\n5. Light jumping jacks and shuffles', 'mobility', ARRAY['setter', 'libero', 'outside_hitter', 'opposite', 'middle_blocker', 'defensive_specialist'], 'beginner', ARRAY['general'], ARRAY['resistance band', 'exercise mat'], 'https://www.youtube.com/results?search_query=volleyball+dynamic+warm+up+routine', NULL, '["Gradual intensity increase", "Full range motion", "Smooth transitions", "Breathing control"]'::jsonb, true);

-- Seed system drills (already exist - shown for reference)
-- These are the 8 system drills from the original seed.sql
-- They will be available to all organizations
